### PR TITLE
fixed processing of unfinished dmc jobs

### PR DESCRIPTION
**Pull request by jaschil2**
Patch for dmc reruns without log files

### CODE REVIEW

**Comment by lkwagner** [comment]
No clue what this is supposed to fix. Please provide documentation on why you changed what you changed.

**Comment by jaschil2** [comment]
Before, if a log file did not appear for some reason, it would not rerun the calculation. Now it does.

**Comment by lkwagner** [comment]
Hi Josh,

Sorry for the slow reply; I was traveling!  This crashes when .log files aren't there; check_status tries to look at a 'None' object.  Please make sure to test carefully on this logic. You should either change check_status to return 'not_finished' if there is a None in the list, or something else.

Cheers

**Comment by jaschil2** [comment]
I must have been working on a different version when I tested it because it worked for me. I will edit it accordingly.

**Comment by lkwagner** [comment]
It's important to make sure that you are up to date (and test carefully!) before initiating a pull request.

**Pull request merged**
