### PR TITLE
Added symmetric geometry input and complex k-point functionality

### PR DESCRIPTION
**Pull request by jaschil2**
-Added cif2crystal symmetric geometry input: cif2geom_sym (not fully tested).
-Added complex k-point functionality to runqwalk. New keyword for job_record['qmc']['dmc']['kpoints']: 'all'.
-Note: I reused get_kpts() code (from RunQWalkDMC class) in Cif2Crystal class. It might be advisable to make the function global in order to eliminate redundancy. I left it as is for now in case there was some reason for having the function specifically in the RunQWalkDMC class.

### CODE REVIEW

**Comment by lkwagner** [comment]
Hi Josh, this has conflicts with the mainline. I can't accept it if that's the case. You need to pull and resolve.

Note that I already implemented a symmetry-preserving cif2crystal, but found some errors. Is yours different than the one I had? Did you test it on a few different materials?

Also, the location for the option seems strange to me. I don't like the idea of crystal2qwalk accessing things in ['qmc']['dmc']. Do you think that it should be in ['qmc'] by itself?

Finally, the list option of ['kpoint'] doesn't seem particularly usable to me; what are the circumstances in which one would use this, since the numbers don't correspond to anything physical? I'd rather not have the option than have something that's awkward like that.

Can you resolve these and re-request? 

Thanks!

**Comment by jaschil2** [comment]
> Hi Josh, this has conflicts with the mainline. I can't accept it if that's the case. You need to pull and resolve.
> 
> Weird. I just forked the mainline to make this repository. I will check what happened and fix it.
> Note that I already implemented a symmetry-preserving cif2crystal, but found some errors. Is yours different than the one I had? Did you test it on a few different materials?

I saw yours. I decided to use pymatgen’s symmetry modules to make the files as I had seen yours was having errors. I’ll test mine further before I resubmit.

> Also, the location for the option seems strange to me. I don't like the idea of crystal2qwalk accessing things in ['qmc']['dmc']. Do you think that it should be in ['qmc'] by itself?

I had considered this, but it was originally in that location and I was hesitant to change it as I figured it was there for a good reason.

> Finally, the list option of ['kpoint'] doesn't seem particularly usable to me; what are the circumstances in which one would use this, since the numbers don't correspond to anything physical? I'd rather not have the option than have something that's awkward like that.

The only reason I implemented this is because in the job_control file it says:

job_record['qmc']['dmc']['kpoints']='real' # or a list of numbers

So I figured you wanted this functionality implemented. I will take it out, though.

**Comment by jaschil2** [comment]
Hello Lucas,

Do you have any of the cifs that gave you issues when using the cif2geom_sym? I want to test my method on those.

Best,
Josh

**Comment by lkwagner** [comment]
@bbusemeyer has a set of test cifs; he might be willing to share them. I seem to remember testing Ni solid, Si solid, and some tetragonal cell. You can get the cifs from ICSD.

**Comment by jaschil2** [comment]
The pull request I just sent should be up to date with the mainline (except changes I made).

**Pull request closed without merging**
